# Enter your server name here.
# Changes in here require a /clarke reload

# This shows up in the StaffChat, and other Commands.
server-name: 'undefined'
# Decides whether or not Mobs should be Smart.
mobAI: true
# Disable the Drowned Spawn Event.
disableDrowned: false
# Disables the Slime Spawn Event.
slimesDisabled: true
# Enables / Disables Global Chat
chat-silenced: false
# When set to FALSE disables the Spawning of Phantoms.
doInsomnia: false
# Default World : Set this to your main world.
world: 'world'
# Disables the creation of Nether Portals
disable-portals: true