name: Atom
version: ${project.version}
main: net.excentrix.core.Core
api-version: 1.16
softdepend: [ LuckPerms, PremiumVanish, SuperVanish ]
loadbefore: [ Essentials ]
depend: [ Vault ]
authors: [ qr0 ]
description: Atom Core Systems.
website: excentrix.net
commands:
  sc:
    description: Communicate with Staff
    usage: /<command>
    aliases: staffchat
    permission: atom.chat.staffchat
  kick:
    description: Remove a player
    usage: /<command>
    permission: atom.command.kick
  report:
    description: Report a player
    default: true
    usage: /<command>
  helpop:
    description: Notify Staff
    default: true
    usage: /<command>
  fly:
    description: Enable Flight
    usage: /<command>
    permission: atom.command.fly
  setserver:
    description: [Admin Only]
    usage: /<command>
    aliases: set-server
    permission: atom.command.setserver
  god:
    description: Make yourself a God
    usage: /<command>
    permission: atom.command.god
  heal:
    description: Heals yourself
    usage: /<command>
    permission: atom.command.heal
  gamemode:
    description: Changes gamemode
    usage: /<command>
    aliases: gm
    permission: atom.command.gamemode
  tp:
    description: Teleports plaers
    usage: /<command>
    aliases: teleport
    permission: atom.command.tp
  kill:
    description: Kills a Player
    usage: /<command>
    permission: atom.command.kill
  atom:
    description: Atom Management Command
    default: true
    usage: /<command>
    aliases: [ help ]
  weather:
    description: Changes the weather
    usage: /<command>
    permission: atom.command.weather
  edit:
    description: Does alot
    usage: /<command>
    permission: atom.command.edit
  freeze:
    description: Halts a players actions
    usage: /<command>
    permission: atom.command.freeze
  smite:
    description: Summons a lightning bold
    usage: /<command>
    permission: atom.command.smite
  enderchest:
    description: Opens the Enderchest
    aliases: [ ec, echest ]
    usage: /<command>
    permission: atom.command.enderchest
  mutelocalchat:
    description: Silences Chat for Non-Staff
    aliases: [ togglechat, mutechat ]
    permission: atom.command.mutelocalchat
  tphere:
    description: Teleports a player to you
    permission: atom.command.tphere
  say:
    description: Broadcast to the Server
    permission: atom.command.say
  grant:
    description: Grants a user a Rank
    usage: /<command>
    permission: atom.command.grant
  grants:
    description: Views a users grants
    permission: atom.command.grants
    usage: /<command>
  give:
    description: Gives a player an Item
    usage: /<command>
    permission: atom.command.give
  togglesc:
    description: Toggles in-game staffchat
    aliases: [ tsm ]
    usage: /<command>
    permission: atom.chat.staffchat
  whisper:
    description: Message a player
    aliases: [ w, msg, tell, t ]
    usage: /<command>
    default: true
  socialspy:
    description: Toggles Admin Spying
    permission: atom.command.socialspy
  togglepm:
    description: Toggles private messaging
    aliases: [ togglepm, tpm ]
    usage: /<command>
    default: true
  announceToStaff:
    description: "Nothing to see here :)"
  setspawn:
    description: Sets the Spawn
    permission: atom.command.setspawn
  spawn:
    description: Teleports to the Spawnpoint
    default: true
  build:
    description: Toggles Build Mode.
    permission: atom.command.build
  balance:
    description: Returns balance
    aliases:
      - bal
  shrug:
    description: "¯\_(ツ)_/¯"
  rankup:
    description: "[Prison] Ranks to the next avail rank."
  togglepvp:
    description: Toggles PVP Globally
    permission: atom.command.togglePvP
  granttoken:
    description: "Generates a Grant Token for the Specified Player with a Specified Grant"