name: Clarke
version: ${project.version}
main: net.excentrix.core.Core
api-version: 1.13
softdepend: [ChatControl]
authors: [qr0]
description: Clarke Management System.
website: clarke.net
commands:
  sc:
      description: Staffchat
      usage: /<command>
      permission: clarke.chat.staffchat
  kick:
    description: Kick
    usage: /<command>
    permission: clarke.command.kick
  report:
    description: Report a player
    default: true
    usage: /<command>
  helpop:
    description: Notify's Staff
    default: true
    usage: /<command>
  fly:
    description: Fly
    permission: clarke.command.fly
    usage: /<command>
  setserver:
    description: [Admin Only]
    permission: clarke.admin
    usage: /<command>
    aliases: set-server
  god:
    description: Set's God Mode
    permission: clarke.command.god