name: Clarke
version: ${project.version}
main: net.excentrix.core.Core
api-version: 1.13
softdepend: [LuckPerms]
depend: []
authors: [qr0]
description: Clarke Management System.
website: excentrix.net
commands:
  sc:
    description: Communicate with Staff
    usage: /<command>
    aliases: staffchat
  kick:
    description: Remove a player
    usage: /<command>
  report:
    description: Report a player
    default: true
    usage: /<command>
  helpop:
    description: Notify Staff
    default: true
    usage: /<command>
  fly:
    description: Enable Flight
    usage: /<command>
  setserver:
    description: [Admin Only]
    usage: /<command>
    aliases: set-server
  god:
    description: Make yourself a God
    usage: /<command>
  heal:
    description: Heals yourself
    usage: /<command>
  gamemode:
    description: Changes gamemode
    usage: /<command>
    aliases: gm
  tp:
    description: Teleports plaers
    usage: /<command>
    aliases: teleport
  kill:
    description: Kills a Player
    usage: /<command>
  clarke:
    description: Clarke
    default: true
    usage: /<command>
  weather:
    description: Changes the weather
    usage: /<command>
  edit:
    description: Does alot
    usage: /<command>
  freeze:
    description: Halts a players actions
    usage: /<command>
  smite:
    description: Summons a lightning bold
    usage: /<command>
  enderchest:
    description: Opens the Enderchest
    aliases: [ec,echest]
    usage: /<command>
  mutechat:
    description: Silences Chat for Non-Staff
  tphere:
    description: Teleports a player to you
  say:
    description: Broadcast to the Server
  grant:
    description: Grants a user a Rank
  give:
    description: Gives a player an Item